volumes:
    blacksmith-data:
        driver: local
services:
    blacksmith-redis:
        image: redis:7-alpine
        ports:
            - "127.0.0.1:2323:6379"
        healthcheck:
            test: redis-cli ping
            interval: 5s
            timeout: 1s
            retries: 5

    blacksmith-postgres:
        image: postgres:latest
        ports:
            - "127.0.0.1:2345:5432"
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - ./blacksmith-data:/var/lib/postgresql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
            start_period: 10s
            timeout: 1s
            retries: 5
            interval: 5s

    mini-kali-slim:
        image: yohannesgk/mini-kali-slim:latest
        container_name: mini-kali-slim
        restart: unless-stopped
        read_only: true
        tmpfs:
          - /tmp
          - /run
          - /var/tmp
          - /var/log
          - /var/lib
          - /var/lock
          - /var/run
        ports:
          - "127.0.0.1:9756:9756"
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:9756/health"]
          interval: 30s
          timeout: 10s
          retries: 3
          start_period: 40s

    blacksmithV1:
        build:
            context: ./blacksmithAI
            dockerfile: Dockerfile
        image: yohannesgk/blacksmith_v1:latest
        ports:
            - "127.0.0.1:2024:8000"
        depends_on:
            blacksmith-redis:
                condition: service_healthy
            blacksmith-postgres:
                condition: service_healthy
            mini-kali-slim:
                condition: service_healthy

        volumes:
            - ./blacksmithAI:/deps/blacksmithAI
        env_file:
            - ./blacksmithAI/.env
        environment:
            REDIS_URI: redis://blacksmith-redis:6379
            DATABASE_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@blacksmith-postgres:5432/${POSTGRES_DB}?sslmode=disable
            container_uri: http://mini-kali-slim:9756/exec

            LANGSERVE_GRAPHS: >-
                {
                  "Orchestrator": "./main.py:main_agent",
                  "ReconnaissanceAgent": "./main.py:reconnaissance",
                  "vulnurabilityMappingAgent": "./main.py:vulnurability_mapping",
                  "PostExploitAgent": "./main.py:post_exploit",
                  "ScannerEnumeratorAgent": "./main.py:scan_enum",
                  "ExploitAgent": "./main.py:exploit"
                }
networks:
  default:
    name: blacksmith-shared
